version: 0.0
os: linux

# Specify files to copy
files:
  - source: /
    destination: /var/www/html/
    overwrite: true

# File permissions after copying
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: apache
    mode: 755
    type:
      - file
      - directory

# Deployment hooks
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  #AfterInstall:
   # - location: scripts/circuit.sh
    #  timeout: 300
     # runas: root
  ApplicationStop:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
